services:
  vue-prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - /var/www/dasssest.com/uploads/:/app/uploads:rw,z
    ports:
      - "5050:80"
    restart: unless-stopped
